import './globals.css';
import { Barlow } from 'next/font/google';
import { AppLayout } from '@/layouts/AppLayout';
import StyledComponentsRegistry from '@/lib/registry';
import { ContextProvider } from '@/providers/ContextProvider';

const inter = Barlow({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={inter.className}>
			<body>
				<StyledComponentsRegistry>
					<ContextProvider>
						<AppLayout>{children}</AppLayout>
					</ContextProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
